
----------------------------------------------------------Revision--------------------------------------------------------------------------------------------

--Car

--Lower Gear has more pulling power hence Torque and need less wheel spin
--Higher Gear has less pulling power hence Torque and need more wheel spin (More Torque at lower gear reduces engines capacity to attain high wheel rpm and vice versa)
--call for more power (go slow with less accelerator(wheel spin)) or release power (go fast with more accelerator (wheel spin))
--3 things to move forward or reverse, torque/pulling force (generated by going down gears and released by going up gears , more engine rpm more pulling force i.e torque), wheel spin(clutch not fully left until proper wheel spin is attained for the gear via accelerator at any gear), momentum (affects whether need first or second, try conserve momentum) 
--trade between torque/pulling force of engine (gears, generate more torque bands by not connecting engine to wheel fully) and wheel spin (accelerator).
--Lower gear has more torque (pulling power Nm) and less accelerating power (BHP Brake Hose Power, wheel spin), 
--Higher gear we go it has lesser torque (pulling power NM) and more accelerating power (BHP, wheel spin, without losses, or Hose Power HP with loss included) . 
--Trade between 2 when driving vehicle. Choose right gears to manage the trade between these two.
--Horsepower is a measure of the power produced by an engine and is often used to describe the acceleration and top speed of a vehicle. 
--Torque is a measure of the twisting force produced by an engine and is often used to describe a 
--vehicle's low-end power and ability to climb hills or carry heavy loads.
--Torque at lower gears, can be achieved at a given RPM achieved by wheel spin hence accelerator .

--Downshift


--clutch full depressed
--break a bit, not complete, to rev match, if gravity is there while going uphill, then donot break (as on higher gear going with less torque / pull and higher wheel spin, reduce the wheel spin via rev match before lower gear )
--choose a lower gear to get more pulling power , so that less wheel spin hence acceleration is needed, mostly for obstacles, optionally can stay in same gear , if feel that current gear can still pull. At first gear maximum pulling force/torque is there, clucth leave very slowly, as if pulling something upward to allow mating of engine with wheels (via clutch, leave from full depressed position) to transfer engine rpm to wheels.Donot leave clutch completely until starts moving. Aid by giving accelerator. 
--(If it was done for a breaker, ease out the brakes a bit before the breaker)
--depressed clutch can pass most obstacles, then leave very slowly as if pulling something upward, aim is that car moves forward or try. Aid by giving accelerator i.e wheel spin, Dont leave clutch completely until correct amount of wheel spin is given with accelerator as per gear.(mostly done at 2nd, 3rd gear or 4th , 5th optionally).clutch should be slowly but eventually released fully once proper wheel spin is achieved as per gear.(at first may decide to not leave clutch fully and shift to second ). 
--Not leaving clutch completely from full depressed position at a gear, aid with accelerator, may make noise, can be used to go slower with some pulling power (this is to use wheel spin with partially left clutch to generate more torque bands i.e pull) (or just shift down with low accelerator(this would generate torque and low wheel spin will be needed)), then leave clutch eventually but slowly when obstacle clear. (may be used in 2nd, also in 1st and reverse (in 1st or reverse it can also be done from top (if already going fast with higher left clutch, not ideal) to slighly low to go slower and eventually stop with mild brake, everything else in 1st, rev, 2nd or higher from full depressed position), to go very slow)
--At uphill or plain (stopped no momentum) do the same, move to lower gear, may be 1st, clutch full depressed, release clutch as if pulling something upwards(car either cross obstacle or stop, trying to go forward), aid by giving accelerator simultaneosly.Donot leave clutch completely until car moves and attain proper wheel spin .
--use momentum with clutch full depressed (mild brake already to rev match), once start getting slow, leave very slow, aid with accelerator, leave only completely when move and attain correct wheel spin by giving accelerator
--(car would tremble if steps are done at higher gear, it would ask a lower gear)
--use momentum for higher gear, if momentum lost switch to lower gear to get more pulling force. 
--leave, give mild break, accelerator in momentum to adjust (full depressed clutch with mild brake will stop eventually, not immediately, use momentum , once start getting slow, leave clutch slowly as if pulling something up, aid with accelerator, don't leave clutch completely, until proper wheel spin is attained with accelerator, once proper wheel spin is attained leave clutch eventually but completely and aid with accelerator, shift up with full depressed, no brake needed, but legs at brake, if car doesnot want to go fast).If wheel spin can't be given, with full depressed clutch and break eventually to stop, shift to lower gear . leave clutch as if pulling something upward, leave mild pressed brakes gradually aid with accelerator. (may move to neutral if stopping then go to first when ready to move).
--legs at full depressed/partially left clutch, brake(adjusted) , or at partially left clutch or full left cutch eventually and accelerator. 
--full depressed clutch and mild amount of break depends on momentum of car (rev match) and slope to full stop (adjust breaking, let loose press more , mild braking wont stop , give control, full breaking to stop), pull fresh from high torque lower gears 1st (if complete stop eventually or immediately) or 2nd or higher (momentum lost) as mentioned above. Optionally stay in same gear and pull as above.
--pressure applied on brakes to rev match depends on speed reduction want and momentum. 
--gradually shift gear up creating momentum, but shift down can be from top to lowest order or any other order depending on rev match . 



--Upshift

--clutch full depressed
--add accelerator and build momentum and good wheel spin(may not needed if gravity is already pulling down at downhill, break well and may go to lower gear in that case to use engine braking)
--break not needed, but body will move legs at break 
--upshift, higher gear has less pulling power, and need more wheel spin
--(car would not want to move, if its wants an even higher gear)
--turned left wheel go left in forward and reverse. Right turned wheel go right in forward and reverse. 

--may park in motion by gear (or momentum) or break (full depressed clutch, mild break, steer where want to) and park.
--don't break suddenly. full depressed, break, as much speed decrease want. shift down 2nd may be, indicator, then position park via 1st gear.

--Please Note:- If rev match not done while downshift with brakes , engine braking would forcefully bring the speed down from high to low to match the speed of the gear.


--Think like a box
--Always make curves and create wide angles. 
--Always watch the mirrors for reversing, (right side mirror), centre mirror for lane change (change only if no vehicle back, road completely visible, if one single road, only if no vehicle for long distance, stay at a lower gear, with pull power, to overtake, with proper accelerator), stay at 4th gear to maximize power on highways.
--Watch out wheels.(wheel alingment with steering).
--while going out of a tight gate or between 2 cars, turn left or right only if half body of car has crossed the obstacle. Both at reversing and going front. 
--going close to wall on right from reverse, turn wheels extreme right, go close to wall in reverse, until some gap left, then turn wheel opposite and then go reverse. (can make angle by going in opposite direction in front). Watch right side mirror. Then straighten wheels. 
--going close to wall on right from forward, turn wheel right. go close to wall in forward, until some gap left, then turn wheel opposite and go forward. Straighten wheels after that. 
--use the same technique if touched a car almost on left, tun wheel a bit right, not extreme and go forward.or turn wheel extreme left and go reverse (may need to go straight). (if touched from reverse on left, slight turn wheel on right, not extrem and go reverse)
--clutch full depressed, mild break, optionally shift down (if uphill or downhill), to go slow at curves, leave clutch slowly, but eventually , aid with accelerarator turn steering towards turn , then straight. Give indicators.
--give horns
--while reversing make angles, see centre , side mirrors, like a box position.
--while turning opposite, on left. turn wheel complete right (depends on space available), go as much possible in front, then wheel extreme opposite and then go reverse, then once space in front turn wheel accordingly (right at available space) and go straight. (may need to do multiple times forward and back to make space, wheel cut depends on space available) 
--both side heavy vehicle, go before comparitvely faster vehicle, go till some distance, then give indicator and then lane change.
--If competing vehicle, slow down to allow go past.
--cross closed parked vehicles, away, straight, cross half, towards, change depends on space 
--use momentum, on depressed clutch, adjust breaks, don't leave clutch completely, until start moving, aid with accelerator (if lost power, switch to lower gear), leave gradullay once proper wheel spin attained with accelerator, switch higher gear then.
--position in centre of a narrow road by going front, before going reverse. 
--Learn to Unlearn, Don't think.
--If front goes towards then back away and vice versa like a box and may be proportional, adjust extremeties and angles based on spaces available and how far left or right currently it is at. The other line is straight where back and front goes in same line. Watch tires for angles. 
--left would go left and right would go right at both front and reverse
--once the car looses momentum by full depressed clutch with mild breaking eventually (done to rev match ) or full breaking immediately,either give more wheel spin by releasing clutch partially, slowly with accelerator, leave clutch completely only once it moves, to match the wheel spin required by gear or if want to give lower accelerator or wheel spin, move to lower gear by full depressed clutch after rev already matched to pull. Never break and accelerate together. May avoid a downshift if before loosing complete momentum , clutch released very slowly fully (or partially) from full depressed position aid with accelerator until moves .break with full depressed clutch and accelerator with partial or fully released clutch adjustments. 
--If close park to wall, move towards wall, then give some space from wall so that orvm mirror passes on straight line. 
--Connect with the vehicle
--At coming out of tight gate, position at the centre, watch side mirrors, as middle mirror won't show on a slope. 
--Sometimes releasing the clutch as if pulling something, may still not be sufficient, vehicle would start coming down at upward slope, for precision stop and not want to come even little. Use hand brake. Pull hand brake. Release clutch as if pulling something. Actual brake not needed. Give accelerator. Car may want to move, make sound . Then ease hand brake. 
--dont cut extreme
--engine rpm, spin hence torque is maximum at lowest gear and hence it needs less wheel spin with accelerator
--clutch propagates the engine spin (ever running when switched on, high or low depends on lower or higer gear) to the wheels by connection. Hence lower gear needs less wheel spin as the engine is rotating at high rpm which is propagated to wheels to keep the vehicle running.Higher gear needs more wheel spin as engine has lost power/torque and rotating with less rpm.
--Donot connect the engine with the wheels completely (donot leave the full depressed clutch (engine, wheel disconnection to change gears. moving as a constraint if full connected) fully, ) until ready to give wheel spin required by the gear, once ready to give the right wheel spin required by gear, clucth must be slowly but eventually released fully and engine connects with wheel, aid with acceleration(wheel spin) .
--If the wheel is not running at the speed gear requires (with accelerator aid or momentum or slope), and the engine is running at low speed (at higher gear), then the car would stop once engine is connected to wheel via releasing full depressed cluctch completely (until not connected fully partially it will not stop), due to less moving power.
--don't cut wheels largely while climbing sharp incline, wheel as straight as possible, maximize surface area. 
--while reversing, use front space as much as possible, side mirrors are critical components while reversing. 
--to come out of back by making some space. Go front in opposite and then cut wheels (away/or straight depending on he gap and angle) and then go back straight. 
--once one wheel pass the speed braker, then leave clucth gently not fully, aid with accelerator. Once ready to give the accelerator required for the gear, leave clutch eventually but fully, aid with accelerator.
--to touch on right wall from back, go left a bit in front to make angle to ease out, then go back, else need to cut extremes. 
--light on pedals.Release light, press light.
--hold the clutch as stable as possible. Feel the engine. Donot leave until ready to give the accelerator required for that gear.
--full depressed clutch with mild, moderate, tight brake adjusted at high speed to stabilize
--at very tight narrow lane, car on left and drain on right, go straight to car, make space straying from orvm and go wide from left as much as possible, then tires would be cut right in making wide angle. Then straighten as much as possible, watch drain on right and adjust wheels accordingly 
--at any gear donot leave the clucth completely, aid with accelerator. until ready to give the accelerator required for the gear. Hold the clucth as steady as 
--possible, be light on accelerator pedal. once ready to give the accelearator required for the gear. Leave the clucth very slowly but eventually aid with accelerator.
--left, right mirrors shows the accurate position of car, watch them and adjust accordingly 
--at turns if momentum there, mostly handle with full depressed clutch and brake, else clutch partially/fully left with accelerator, depends on momentum and gradient. 
--steering like handle, turn towards and opposite, (also straighten) as required depends on space and place, guide based on place.
--touch towards right wall from back, wheel is turned right, approach wall, back wheel is like an axial, turn wheel left, to go left in back from that position itself or straighten. May not go any further back doing so
--go at 90 degree, first go at 75 deg (bigger the angle, going back and lesser need to cut wheels opposite), then reverse and try to meet 90 degree, may not be straight line, but a curve trying to go towards straight line. 
--full depressed clutch with mild (eventually stop, not sharp) or sharp break (for uphill, control), forward or reverse.
--wheel straighter, maximum surface area, greater climbing surface. 
--coming out between 2 cars in back, let car body cross half, then cut opposite as much as space possible, and go back, stop, then cut opposite and go front as much 
--possible and then again go back (and repeat if required) to make space. (if close to some side, may need to come straight, or turn wheel opposite , if 
--touching more on left, turn right)
--coming  between two/one vehicles
--if more touch on left and coming back, then turn wheel left (same side) and/or straight (turn same side and straighten otherwise space would become less on other side), move back, once the distance of the back side of the
--vehicle starts becoming less and some gap is created on the front side, turn wheels opposite and move back. Then later go straight making some wide spaces.
--if more touch on left and going front little on left, then turn right (opposite side) and/or straight (then again left/straight depending on space) (turn opposite side and straighten otherwise space would become less on other side)
--if both sides close , then come back , front straight. watch wheels.
--but to park reverse or forward, when not already standing between 2 vehicles
--then right moves right and left moves left, straight moves straight, make wide spaces, see back for clearance, position like a box, turn steering accordingly
--make spaces , wide curves by going away from obstacles and then turning/creating angles.
--may need to cut in different direction depending on space and obstacle. 
--avoid crossing between 2 obstacles at an angle.
--full depressed clutch, brake (depends on the gradient), key ignition to start, half key ignition switch on battery power, full ignition starts fuel power. 
--dont leave the clutch completely until from full depressed position aid with accelerator until ready to give the accelerator required for that gear , to create variable, infinite gear ratios. 
--to position park in between 2 vehicles, first go towards vehicle on left and then cut wheels right and then go straight.
--if more touch towards left, and want to come in reverse, turn wheels towards left, and move back (If space is there is front, go front in left, and turn wheel
--right (going further in left is a way to make some space , to be able to tun wheel right and go back) and come back and straighten), if more touch on left and no space in front, turn wheel right (make sure not a vehicle)
--and go back and straighten. (starighten is required as otherwise back would become closer to right).May need to do multiple times.
--if more touch on left and want to go front, turn wheel opposite and go front.


--Reverse Techniques (under test)
--go front, create angle, then cut wheels opposite to the reverse direction to make space
--move like a box , right makes go right, left makes go left, in forward and reverse, if all clear back, then go back
--then cut complete towards where want to reverse and go back, make wide spaces while going back or front
--see left and right mirrors and wherever gap become less, go opposite to make it more 
--may need to go front or back to adjust
--at reverse make sure under car mirror, shows no vehicle at back. 
--left and right mirrors are critical components of reversing


--Some lessons
--adopt light foot driving
--in turns , cut complete , so that able to cut complete in one go.
--may use empty spaces at left/right to cut complete.
--in tight entrances, exit, try to kepp the vehicle as straight as possible, going at angles are risky.
--cut extremes forward snd reverse, left or right depending on space available, to u turn in small space, adjust as per space.
--left steer goes left, right steer goes right in both forward and reverse


--parking

--decide to go opposite direction (or towards the original position from where started)

--withdraw is always with wheel in same direction (want to move back and space becoming less, 
--then if need to go front to make angle go front with same wheel direction, after that make angle by turning wheel opposite and going back and 
--after than once space is created
--turn wheel back as was initially intended and go back)

--(want to move front, and if need to go back to make angle go back with wheel in same direction then make angle by turning wheel opposite and going front
--and once angle is created
--then go front as was initially intended with the same direction wheel )
--optionally straight also 


--still going in same direction (or in a different direction than the original position from where started)

--commit is always with wheel in same direction, if going front and touched on one side more, turn wheel opposite and still go front 
--if going back and touched more on one side , turn wheel opposite and still go back 
--may optional straight 

--in gear (not neutral) always means motion if clutch is not fully pressed.


--summary
--full depressed clutch, mild clutch adjusted to use momentum (also for eventual stop)
--If lost momemtum, choose right lower gear
--don't leave the clutch completely until ready to give the accelerator required by the gear, and car starts moving, aid with accelerator (slowly but completely leave the accelerator)
--Only clutch to shift up, after increasing accelerator  (unless gravity increase speed, then break)
--clutch break , rev match, then lower gear accordingly (unless gravity slows down, then no break)
--hose power, torque concept, more than gear higher the hose power, lower the torque, lower the gear higher the torque, lesser the hosepower.
--engine constant rotating, start connecting with wheel when clutch is left slowly, engine get disconnected from wheel on clutch depressed.
--lesser the clutch leave at gears, aid with accelerator, lesser the speed with which car moves, allows change of angles in motion, more the clutch left faster the motion, aid with accelerator, full depressed, mild brake adjusted to adjust speed, moving engine and wheel, need some mating time, more the gear, more the mating time, aid with accelerator.
, however If the speed of car is more at any gear, full depressed clutch , mild brake adjusted, mild brake doesn't fully stop vehicle, to lower speed and then adjust angle with steering, use momentum, then again leave full depressed clutch very slowly, aid with accelerator, might need to fully stop with full depressed clutch and full brake, then change angle, then again leave full depressed clutch very slowly, aid with accelerator, lower gear if momentum lost
--can change angles in motion , if empty spaces
--steering like precise handle, turn front wheel 
--mirrors
--multiple permutations, combinations , by the great God




--Scooter 

--scooter, position it same as car
--accelerate gentle or hard, dont break simulaneously.
--adjust mild or hard break, left mostly, then leave left break and accelerate, mild left not stop fully, near breaker, left brake first not stop completely then right break to further drop speed, might decide to hold or leave depending on the momentum of the vehicle generated by wheel spin, adjust with left break and then right break, one tyre cross breaker, then accelerate mildly.
--use momentum if possible, hard without clutch
--mirror, horn, lane change as per car.
--if wheel spin momentum lost due to break or no wheel spin accelerator given or uphill, generate wheel spin or accelerator . 
--left brake (mild stop, speed down), then right brake at speed braker (tighter stop), once one wheel pass the braker , then accelerate.
--mild accelerator, brake to move slow
--cvt has infinite gear ratios 
--progressive breaking like car, conserve momentum, light accelerator
--centre stand, left leg, apply downward pressure, hold back handle, upward pressure
--mild left break, eventually to stop, them mild accelerator
